### ISSUE TITLE
rec: handle negative answers with scope > 0 as if they have scope 0

### ISSUE THREAD

**Issue by yang-xixi** [PowerDNS/pdns#10994]
- Program: Recursor
 - Issue type: Bug report

### Short description
When dnssec and ecs are both enabled, query to **tosei-hotel.co.jp.e.afq.hp.transer.com.cdn.cloudflare.net** will timeout with servfail and trace-regex shows looped DNS recursion. This can be reproduced on latest 4.4 and 4.3 but not 4.5.

### Environment

 - Operating system: Ubuntu 20.04
 - Software version: 4.4.7 or 4.3.7
 - Software source: PowerDNS repository http://repo.powerdns.com/ubuntu

### Steps to reproduce
1. Install pdns-recursor 4.4.7 on Ubuntu Focal
2. recurse.conf
```
dnssec=validate
local-address=0.0.0.0, ::
loglevel=9
threads=1
edns-subnet-whitelist=cloudflare.net
```
3. Run
```
rec_control trace-regex 'tosei-hotel\.co\.jp\.e\.afq\.hp\.transer\.com\.cdn\.cloudflare\.net' &&
    dig @127.0.0.1 tosei-hotel.co.jp.e.afq.hp.transer.com.cdn.cloudflare.net`
```

### Expected behaviour
Resolution should succeed.

### Actual behaviour
Servfail response.

**Comment by omoerbeek** [comment]
Thanks for the report. I can reproduce on 4.4.x.
The recursion is actually not infinite. If you set `max-qperq=260` the resolving works.
With 4.4.x, it looks like this hits a case where the caching of some records is not happening or is not effective, so the recursor needs a lot of queries to resolve the name.

Will investigate some more.

**Comment by omoerbeek** [comment]
On further analysis: cloudflare is not following 

https://datatracker.ietf.org/doc/html/rfc7871#section-7.4.

Specifically, negative answers should use zero scope. However:

```
$ dig cdn.cloudflare.net DS @173.245.59.31 +dnssec +subnet=192.0.2.1/24

; <<>> DiG 9.16.22 <<>> cdn.cloudflare.net DS @173.245.59.31 +dnssec +subnet=192.0.2.1/24
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9541
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 4, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1232
; CLIENT-SUBNET: 192.0.2.0/24/24
```
The consequence is that we do not cache this negative indication and re-query this all the time for zone-cut determination.
4.5.x does not suffer because it has a completely different way of determining zone cuts.

**Comment by omoerbeek** [comment]
I changed the title to reflect the root cause of the issue.

**Comment by yang-xixi** [comment]
Thank you Otto for your quick response. For me the max-qperq has to be set to 400 for 4.4.7 to resolve this name. It will still timeout on first query due to the number of queries required but pdns will cache the answer for later queries. I will report to cloudflare and see if they can do anything about it.

Meanwhile, according to RFC7871, it seems OK for resolver to assume scope 0 for negative answers. In reality, I can't think of many scenarios that scoped negative answer would be useful. Can we expect this interoperability issue to be worked around in 4.4.x?

**Comment by omoerbeek** [comment]
We are currently investigating how to fix this. After we have a fix, we will check if it can be backported to 4.4.x

**Comment by hunts** [comment]
Hi from Cloudflare DNS team. Thank you for reporting the issue, we've released a fix for it. You should find it works as expected now.

**Comment by omoerbeek** [comment]
I'm now seeing /0 for the negative answers indeed. This is not enough to solve the issue on our side though, since an intermediate result carrying answer records (e.g. as a result of an A query) still gets a scope > 0, marking the whole resolving process variable. So the fix in #11010 is still needed and should be backported.

**Comment by omoerbeek** [comment]
As a workaround until a fixed 4.4.x is released , setting `qname-minimization=off` avoids the problems in cases I tried, though in theory if a scoped intermediate result lands in the cache via another query I think the issue could still be hit.
