### ISSUE TITLE
bindbackend referrals get auth=0 error from check-zone

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdns#8184]
- Program: Authoritative
 - Issue type: Bug report

### Short description

NS records for sub-zones on the same server make pdnsutil complain `Following record is auth=0, run pdnsutil rectify-zone?`

See below for example. Note that both zones are hosted by bindbackend.

```
root@ns1:/etc/powerdns/zones.master.d# pdnsutil list-zone deduktiva.dev
Aug 09 19:09:58 [bindbackend] Done parsing domains, 0 rejected, 15 new, 0 removed
$ORIGIN .
deduktiva.dev	14400	IN	SOA	ns1.namespace.at dns.namespace.at 27 10800 3600 604800 14400
deduktiva.dev	14400	IN	NS	ns1.namespace.at.
deduktiva.dev	14400	IN	NS	ns2.namespace.at.
deduktiva.dev	3600	IN	A	213.208.148.231
test1.deduktiva.dev	3600	IN	NS	ns1.namespace.at.
www.deduktiva.dev	3600	IN	A	213.208.148.231

root@ns1:/etc/powerdns/zones.master.d# pdnsutil list-zone test1.deduktiva.dev
Aug 09 19:10:01 [bindbackend] Done parsing domains, 0 rejected, 15 new, 0 removed
$ORIGIN .
test1.deduktiva.dev	14400	IN	SOA	ns1.namespace.at dns.namespace.at 27 10800 3600 604800 14400
test1.deduktiva.dev	14400	IN	NS	ns1.namespace.at.
test1.deduktiva.dev	14400	IN	NS	ns2.namespace.at.

root@ns1:/etc/powerdns/zones.master.d# pdnsutil check-zone test1.deduktiva.dev
Aug 09 19:10:10 [bindbackend] Done parsing domains, 0 rejected, 15 new, 0 removed
Checked 3 records of 'test1.deduktiva.dev', 0 errors, 0 warnings.

root@ns1:/etc/powerdns/zones.master.d# pdnsutil check-zone deduktiva.dev
Aug 09 19:10:12 [bindbackend] Done parsing domains, 0 rejected, 15 new, 0 removed
[Error] Following record is auth=0, run pdnsutil rectify-zone?: test1.deduktiva.dev IN NS ns1.namespace.at
Checked 6 records of 'deduktiva.dev', 1 errors, 0 warnings.
```

bindbackend config is:
```
launch+=bind
bind-config=/etc/powerdns/named.conf
```

```
zone "deduktiva.dev" {
  file "/etc/powerdns/zones.master.d/deduktiva.dev.zone";
  type master;
};
zone "test1.deduktiva.dev" {
  file "/etc/powerdns/zones.master.d/test1.deduktiva.dev.zone";
  type master;
};
```

I've omitted the config for zones that shouldn't be relevant here.

Maybe I'm holding sth wrong?

### Environment

 - Operating system: Debian stretch
 - Software version: 4.2.0~rc2-1pdns.stretch
 - Software source: repo.powerdns.com

**Comment by mind04** [comment]
Please re-check with rc3, since #8184 is related to this issue.

**Comment by Habbie** [comment]
This is #8184..

**Comment by mind04** [comment]
oops,  #8092

**Comment by zeha** [comment]
Just rechecked with rc3, unchanged output.

**Comment by mind04** [comment]
This is a pdnsutil bug. pdnsutil is unable to deal with properly set auth values from a non dnssec capable backend (bind without a dnssec db)

**Comment by jeremy-clerc** [comment]
We have a tool that generates our zones, then use `pdnsutil check-zone` before using them (it works in 4.1), but we do not use dnssec.
We would like to upgrade to 4.2 to use some new features/options.

So I am looking into creating a patch.

If I correctly understand this block: https://github.com/PowerDNS/pdns/blob/master/pdns/pdnsutil.cc#L566-L599 it validates if we have a NS record for a delegation, there should be a DS associated, and vice versa, that there is no DS without NS.
So it is only useful for dnssec ?

So what like to do is either skip the all block if it does not do dnssec as we are `done = true` anyway
```
if (sd.db->doesDNSSEC()) {
  for( const auto &rr : records ) {
  }
}
```
or https://github.com/PowerDNS/pdns/blob/master/pdns/pdnsutil.cc#L595 do not count an error if does not do dnssec `if( ! ok && ! suppliedrecords && sd.db->doesDNSSEC()) {`

You see other ways ? Changing auth to 1 if not dnssec ?

**Comment by miodvallat** [comment]
I am unable to reproduce this; my understanding is that the "does this backend does DNSSEC" check is enough - it causes the `done` variable to be true which in turn causes the complain message to be skipped.

But then that logic was already present at the time this issue was reported, so I am not sure what I am missing here.

With a simple setup similar to the OP's, I get no errors and no warning from `pdnsutil zone check` of the sub zone.

**Comment by zeha** [comment]
Been a while. Maybe zonecache masks the problem, or it was fixed in some other place?

**Comment by miodvallat** [comment]
This is a `pdnsutil` issue, I doubt the zone cache contributes to anything in it :)

**Comment by zeha** [comment]
That's what I get for answering in the middle of something else.

**Comment by mind04** [comment]
issue is still there. 

Run in the regression-tests directory:
```
./start-test-stop 5300 bind
../pdns/pdnsutil --config-dir=./ --config-name=bind check-zone cryptokeys.org
```

**Comment by miodvallat** [comment]
@mind04 thanks for a working reproducer!

**Comment by jeremy-clerc** [comment]
Hello,

Fun thing, at least a good surprise to me, as we are looking to upgrade pdns without keeping our internal patch (#8620) and internally built RPM, I dig again in this issue, eventual new settings, disabling whatever I can, ... anyway.

Having an empty `bind-dnssec-db` is enough to not have pdnsutil complain (With pdns auth-5)

```
$ pdnsutil create-bind-db /var/lib/powerdns/bind-dnssec-db.sqlite3
```

`pdns-authoritative.conf`:
```
bind-dnssec-db=/var/lib/powerdns/bind-dnssec-db.sqlite3
```

I do not know if it is an unattended side effect ? But enough to unblock us and get back on a clean track.
